trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Docker@2
    displayName: Login Docker
    inputs:
      containerRegistry: "docker_registry_oracle"
      command: "login"

  - task: Docker@2
    displayName: Build and Push an image
    inputs:
      containerRegistry: "docker_registry_oracle"
      repository: "armpb/tela-erros"
      command: "buildAndPush"
      Dockerfile: "$(System.DefaultWorkingDirectory)/Dockerfile"
      tags: "latest"

  - task: Docker@2
    displayName: Logout Docker
    inputs:
      containerRegistry: "docker_registry_oracle"
      command: "logout"
